### ISSUE TITLE
Include sample data and test

### ISSUE THREAD

**Issue by buddha314** [benharsh/chapel#3]
BH, do you have some sample data and/or a test I can run?

**Comment by benharsh** [comment]
I'll commit one in a moment.

**Edit**: maybe a little more than a moment, need to write a better program to generate data.

**Comment by benharsh** [comment]
Just pushed a CSV generator and a sample program.

Unfortunately, it seems like there's a bug with matrix-matrix multiplication for certain sparse arrays. I'm looking into it now.

**Comment by benharsh** [comment]
Just pushed some changes that appear to resolve the bugs I was seeing. Notably the LinearAlgebra package itself needed to be modified.

**Comment by benharsh** [comment]
The change to LinearAlgebra does more sorting, so performance is a bit worse. Some quick experiments suggest a 20% hit. I'm not sure how we compare to python yet.

**Comment by buddha314** [comment]
Before BA left, he said he was out-performing python.  I hope that was by about 21%! How do I use the changes LinearAlgebra package?

**Comment by benharsh** [comment]
The easiest way would be to copy this file into your local build of Chapel:

https://github.com/benharsh/chapel/blob/sparse-csv-bin/modules/packages/LinearAlgebra.chpl

At least until I get it reviewed + merged on master.

**Comment by benharsh** [comment]
PR against master has been opened:

https://github.com/chapel-lang/chapel/pull/7520

**Comment by benharsh** [comment]
Those changes to LinearAlgebra.Sparse are now on master.

**Comment by benharsh** [comment]
Should this issue be closed?

**Comment by buddha314** [comment]
Yes, I think so.  Want to do the honors?
